FROM nginx:alpine

# Copy nginx template and entrypoint script
COPY frontend/nginx.template /etc/nginx/conf.d/nginx.template
COPY frontend/docker-entrypoint.sh /docker-entrypoint.sh
RUN chmod +x /docker-entrypoint.sh

# Copy frontend files
COPY frontend/src /usr/share/nginx/html

# Add script to handle environment variables
ENTRYPOINT ["/docker-entrypoint.sh"]
CMD ["nginx", "-g", "daemon off;"] 