services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    volumes:
      - ./backend/data:/app/backend/data
      - ./backend/logs:/app/backend/logs
      - ./.env:/app/.env:ro
    ports:
      - "${API_PORT:-8000}:8000"
    environment:
      - TZ=UTC
      - API_PORT=${API_PORT:-8000}
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "${FRONTEND_PORT:-3000}:80"
    environment:
      - API_PORT=${API_PORT:-8000}
    depends_on:
      - backend 