services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./backend/data:/app/backend/data
      - ./backend/logs:/app/backend/logs
      - ./.env:/app/.env:ro
    ports:
      - "${FRONTEND_PORT:-3000}:80"
    environment:
      - TZ=UTC
      - API_PORT=${API_PORT:-8000}
    restart: unless-stopped 