version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    volumes:
      - ./backend/data:/app/backend/data
      - ./backend/logs:/app/backend/logs
      - ./.env:/app/.env:ro
    ports:
      - "8000:8000"
    environment:
      - TZ=UTC
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:80"
    environment:
      - API_URL=http://localhost:8000
    depends_on:
      - backend 